language: csharp
mono: none
dotnet: 2.1.302
solution: TestCI.sln

install:
  - dotnet restore
  # - dotnet add package xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - dotnet build